apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: obcluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: 500M
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards
            name: grafana-providers
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards/template
            name: grafana-dashboards-ob
            readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: local-path-grafana
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: grafana-providers
          configMap:
              defaultMode: 0777
              name: grafana-providers
        - name: grafana-dashboards-ob
          configMap:
              defaultMode: 0777
              name: grafana-dashboards-ob
