apiVersion: v1
kind: Secret
metadata:
  name: tenant1-root-password
  namespace: obcluster
data:
  # base64 encoded
  user: cm9vdAo=
  password: ******
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant1-backup
  namespace: obcluster
data:
  incremental: cHdkMV9pbmNyZW1lbnRhbAo=
  full: cHdkMV9kYXRhYmFzZQo=

---
apiVersion: v1
kind: Secret
metadata:
  name: tenant2-root-password
  namespace: obcluster
data:
  # base64 encoded
  user: cm9vdAo=
  password: ******
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant2-backup
  namespace: obcluster
data:
  incremental: cHdkMl9pbmNyZW1lbnRhbAo=
  full: cHdkMl9kYXRhYmFzZQo=
