apiVersion: v1
kind: Secret
metadata:
  name: tenant1-root-password
  namespace: obcluster
data:
  user: cm9vdAo= #root
  password: cHdkMQo= #pwd1
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant1-backup
  namespace: obcluster
data:
  incremental: cHdkMV9pbmNyZW1lbnRhbAo= #pwd1_incremental
  database: cHdkMV9kYXRhYmFzZQo= #pwd1_database

---
apiVersion: v1
kind: Secret
metadata:
  name: tenant2-root-password
  namespace: obcluster
data:
  user: cm9vdAo=
  password: cHdkMgo=
---
apiVersion: v1
kind: Secret
metadata:
  name: tenant2-backup
  namespace: obcluster
data:
  incremental: cHdkMl9pbmNyZW1lbnRhbAo=
  database: cHdkMl9kYXRhYmFzZQo=