# permissions for end users to view restores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restore-viewer-role
rules:
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - restores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.oceanbase.com
  resources:
  - restores/status
  verbs:
  - get
