{{- if .Values.cert-manager.enabled }}
  {{- $crdName := "certificates.cert-manager.io" }}
  {{- if not (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" $crdName) }}
    {{- printf "Installing cert-manager..." | nindent 2 }}
    {{ template "cert-manager.subchart" . }}
  {{- else }}
    {{- printf "cert-manager is already installed, skipping..." | nindent 2 }}
  {{- end }}
{{- else }}
  {{- printf "cert-manager installation is disabled" | nindent 2 }}
{{- end }}

