apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ob-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://oceanbase.github.io/ob-operator
    chart: obproxy-ce
    targetRevision: 0.1.0
    helm:
      parameters:
      - name: obcluster
        value: "obcluster"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: oceanbase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
