apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-generator-sa
  namespace: oceanbase

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-generator-role
  namespace: oceanbase
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-generator-rb
  namespace: oceanbase
subjects:
- kind: ServiceAccount
  name: secret-generator-sa
roleRef:
  kind: Role
  name: secret-generator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-ob-password
  namespace: oceanbase
  annotations:
    argocd.argocroj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: secret-generator-sa
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - "kubectl get secret root-password -n oceanbase || kubectl create secret generic root-password -n oceanbase --from-literal=password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16); kubectl get secret proxyro-password -n oceanbase || kubectl create secret generic proxyro-password -n oceanbase --from-literal=password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16); kubectl get secret monitor-password -n oceanbase || kubectl create secret generic monitor-password -n oceanbase --from-literal=password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16); kubectl get secret operator-password -n oceanbase || kubectl create secret generic operator-password -n oceanbase --from-literal=password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16); kubectl get secret standbyro-password -n oceanbase || kubectl create secret generic standbyro-password -n oceanbase --from-literal=password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16); kubectl get secret tenant-root-password -n oceanbase || kubectl create secret generic tenant-root-password -n oceanbase --from-literal=password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16)"
  backoffLimit: 1
