package rules

import (
	"github.com/antlr4-go/antlr/v4"
	"github.com/oceanbase/ob-operator/internal/sql-analyzer/api/model"
	obmysql "github.com/oceanbase/ob-operator/internal/sql-analyzer/parser/mysql"
	logger "github.com/sirupsen/logrus"
)

// SelectAllRule checks for the usage of SELECT *
type SelectAllRule struct {
	// Embed the BaseOBParserVisitor to get default no-op implementations
	// Note: This assumes BaseOBParserVisitor is generated by ANTLR with the -visitor flag
	*obmysql.BaseOBParserVisitor
	diagnoseResults []model.SqlDiagnoseInfo
}

// NewSelectAllRule creates a new SelectAllRule
func NewSelectAllRule() *SelectAllRule {
	return &SelectAllRule{
		BaseOBParserVisitor: &obmysql.BaseOBParserVisitor{},
	}
}

// Name returns the name of the rule
func (r *SelectAllRule) Name() string {
	return "select_all_rule"
}

// Description returns the description of the rule
func (r *SelectAllRule) Description() string {
	return "Avoid using SELECT * in queries."
}

// Analyze traverses the parse tree to find SELECT * statements
func (r *SelectAllRule) Analyze(tree antlr.ParseTree, indexes []model.IndexInfo) []model.SqlDiagnoseInfo {
	r.diagnoseResults = []model.SqlDiagnoseInfo{} // Reset results for each analysis

	// We manually walk the tree since ANTLR4 Go visitors don't have a generic "Walk" method that takes a visitor.
	// Instead, we use the Accept method on the tree which dispatches to the visitor.
	// However, standard Accept returns interface{}, so we need to ensure our visitor methods
	// traverse children correctly to cover the whole tree.

	// For "Select *" specifically, we are looking for 'projection' nodes.
	// We rely on the tree's Accept method to start the process.
	logger.Debugf("[SelectAllRule] Starting analysis")
	tree.Accept(r)

	return r.diagnoseResults
}

// VisitProjection is called when the visitor encounters a 'projection' rule.
// Matches: projection : bit_expr | bit_expr AS? column_label | bit_expr AS? STRING_VALUE | Star ;
func (r *SelectAllRule) VisitProjection(ctx *obmysql.ProjectionContext) interface{} {
	logger.Debugf("[SelectAllRule] Visiting Projection. Text: %s", ctx.GetText())
	if ctx.Star() != nil { // Check if the '*' token exists in this projection context
		logger.Debugf("[SelectAllRule] Found Star in Projection")
		r.diagnoseResults = append(r.diagnoseResults, model.SqlDiagnoseInfo{
			RuleName:   r.Name(),
			Level:      "WARN",
			Suggestion: "Specify specific columns instead of using SELECT * to improve performance and clarity.",
			Reason:     "Using SELECT * retrieves all columns, which can be inefficient and return unnecessary data.",
		})
	} else {
		logger.Debugf("[SelectAllRule] No Star in Projection")
	}
	// Continue visiting children to ensure we don't miss nested queries
	return r.BaseOBParserVisitor.VisitChildren(ctx)
}
